name: awaken
favicon: null
layout_spectrum: 0.3426902594510466
typography_spectrum: 0.02202517888508737
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.438372345874086
  lightness: 0.3365961932577193
  saturation: 0.6975917613599449
  rhythmicContrast: 0.08391407690942287
purpose: []
